#!/usr/bin/env bash
# B-28's measurement: the first load of the storefront's production wasm bundle — sizes per file, raw,
# gzip and brotli, and the time to the first frame in headless Chromium under three network profiles.
# The measuring itself is scripts/measure-first-load.py; this script builds the two arms and runs it.
#
#   main   — the bundle as `main` builds it. Its root draws the theme with an empty body, so nothing
#            calls the renderers and dead-code elimination is free to leave them out.
#   wired  — a throwaway copy of the tree whose root renders the Home body of the screenshot fixtures
#            (composeApp/src/desktopTest/resources/bodies/home_content.json) through haulRegistry():
#            every renderer reachable, real text drawn in the three fonts. Nothing of it is committed.
#
# Neither arm needs the server or PostgreSQL: the page is static files and the wired arm's body is
# compiled in. Outputs go to $OUT (raw runs as JSON lines, a summary per arm, a screenshot per run).
#
#   scripts/measure-first-load.sh [rounds]
#
# GRADLE overrides the Gradle invocation, e.g. to cap memory on a shared box:
#   GRADLE='systemd-run --user --scope -p MemoryMax=5G -p MemorySwapMax=0 ./gradlew --max-workers=2
#           -Pkotlin.compiler.execution.strategy=in-process -Dorg.gradle.daemon=false'
# ARMS picks the arms (default "main wired"); CHROME_BIN the Chromium (default: Playwright's).
set -u
cd "$(dirname "$0")/.."
ROUNDS=${1:-7}
OUT=${OUT:-/tmp/b28-first-load}
WORK=${WORK:-/tmp/b28-wired-tree}
GRADLE=${GRADLE:-./gradlew}
ARMS=${ARMS:-main wired}
DIST=composeApp/build/dist/wasmJs/productionExecutable
mkdir -p "$OUT"
status=0

build() { # $1 = tree, $2 = log
  (cd "$1" && $GRADLE :composeApp:wasmJsBrowserDistribution > "$2" 2>&1) || { echo "build failed: $2"; exit 1; }
}

for arm in $ARMS; do
  case $arm in
    main)
      tree=$PWD
      ;;
    wired)
      tree=$WORK
      rm -rf "$tree" && mkdir -p "$tree"
      tar --exclude=./.gradle --exclude=./.kotlin --exclude='*/build' --exclude=./.git -cf - . | tar -xf - -C "$tree"
      python3 - "$tree" <<'EOF'
import json, sys
tree = sys.argv[1]
body = open(f"{tree}/composeApp/src/desktopTest/resources/bodies/home_content.json").read()
literal = json.dumps(json.dumps(json.loads(body))).replace("$", "\\$")
pkg = f"{tree}/composeApp/src/wasmJsMain/kotlin/io/github/youndie/haul"
open(f"{pkg}/MeasureWired.kt", "w").write('''package io.github.youndie.haul

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import io.github.youndie.haul.registry.haulJson
import io.github.youndie.haul.registry.haulRegistry
import io.github.youndie.haul.theme.HaulColors
import io.github.youndie.haul.theme.HaulTheme
import io.github.youndie.haul.theme.rememberHaulFonts
import io.github.youndie.haul.ui.LocalHaulNow
import io.github.youndie.kompot.KompotActionHandler
import io.github.youndie.kompot.KompotComponent
import io.github.youndie.kompot.KompotScreen
import io.github.youndie.kompot.form.FormController
import io.github.youndie.kompot.form.FormSchema
import kotlinx.serialization.PolymorphicSerializer
import kotlin.time.Instant

// B-28's wired arm, generated by scripts/measure-first-load.sh into a throwaway copy of the tree.

@Composable
internal fun WiredHome() {
    val body = remember { haulJson.decodeFromString(PolymorphicSerializer(KompotComponent::class), HOME_BODY) }
    val registry = remember { haulRegistry() }
    val forms = remember { FormController(FormSchema(formId = "none", fields = emptyList())) }
    BoxWithConstraints(Modifier.fillMaxSize().background(HaulColors.background)) {
        HaulTheme(rememberHaulFonts(), compact = maxWidth < 768.dp) {
            CompositionLocalProvider(LocalHaulNow provides Instant.parse("2025-10-07T19:47:23-04:00")) {
                Box(Modifier.fillMaxSize().verticalScroll(rememberScrollState())) {
                    KompotScreen(body, registry, forms, KompotActionHandler { })
                }
            }
        }
    }
}

private const val HOME_BODY: String = ''' + literal + '''
''')
main = f"{pkg}/Main.kt"
src = open(main).read()
assert "{ App() }" in src, "Main.kt changed: update the wired arm's patch"
open(main, "w").write(src.replace("{ App() }", "{ WiredHome() }"))
EOF
      ;;
    *) echo "unknown arm $arm"; exit 2 ;;
  esac
  build "$tree" "$OUT/$arm-build.log"
  sha256sum "$tree/$DIST"/*.wasm > "$OUT/$arm-wasm.sha256"
  python3 scripts/measure-first-load.py "$tree/$DIST" "$OUT" --rounds "$ROUNDS" --label "$arm" > "$OUT/$arm.log" 2>&1 || status=1
  tail -n +1 "$OUT/$arm-summary.md" 2>/dev/null || cat "$OUT/$arm.log"
done
exit $status
